# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' @title CovToPrecisionCholcpp
#' @keywords internal
#' @export
CovToPrecisionChol_cpp <- function(L, Sigma) {
    .Call('EmpericalSparsePrecision_CovToPrecisionChol_cpp', PACKAGE = 'EmpericalSparsePrecision', L, Sigma)
}

#' @title reordercpp
#' @keywords internal
#' @export
reorder_cpp <- function(K) {
    .Call('EmpericalSparsePrecision_reorder_cpp', PACKAGE = 'EmpericalSparsePrecision', K)
}

#' @title symbolicCholeskyFactorcpp
#' @keywords internal
#' @export
symbolicCholeskyFactor_cpp <- function(K) {
    .Call('EmpericalSparsePrecision_symbolicCholeskyFactor_cpp', PACKAGE = 'EmpericalSparsePrecision', K)
}

